name: Build Dipper Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout kernel
        uses: actions/checkout@v4
        with:
          ref: dipper-q-oss
          fetch-depth: 1

      - name: Test runner
        run: |
          echo "GitHub Actions runner OK"
          uname -a
          make --version
          clang --version
